import Link from'next/link';
const previews=[['LRSS na prática','Organize responsabilidades, evidências e a rotina documental da clínica.','8 aulas'],['Gestão sanitária odontológica','Transforme exigências em processos simples de acompanhar.','7 aulas'],['Biossegurança para equipes','Capacite a equipe com aulas curtas e aplicáveis.','6 aulas']];
export default function Home(){return <>
  <section className="wrap hero learning-hero"><div><p className="eyebrow">CAPACITAÇÃO B2B PARA ODONTOLOGIA</p><h1>Conhecimento que vira rotina na sua clínica.</h1><p className="lead">Cursos em vídeo para responsáveis e equipes odontológicas implantarem conformidade, biossegurança e gestão sanitária com segurança e continuidade.</p><div className="actions"><Link className="btn primary" href="/checkout">Assinar a plataforma</Link><Link className="btn" href="/cursos">Explorar cursos</Link></div><p className="micro">Conta individual da clínica · Contrato de 24 meses · Acompanhamento de progresso</p></div><div className="video-preview"><span>PRÉVIA GRATUITA</span><div className="play">▶</div><h3>LRSS na prática</h3><p>Veja como transformar a conformidade em uma rotina acompanhável.</p></div></section>
  <section className="section"><div className="wrap"><p className="eyebrow">TRILHAS PARA O TRABALHO REAL</p><h2>Comece pelo desafio mais urgente da clínica.</h2><div className="course-grid">{previews.map(([title,text,count],i)=><article className="course-card" key={title}><div className={`course-cover cover-${i+1}`}><span>{count}</span><b>▶</b></div><div><small>CURSO ONLINE</small><h3>{title}</h3><p>{text}</p><Link href="/cursos">Ver conteúdo do curso →</Link></div></article>)}</div></div></section>
  <section className="section platform-band"><div className="wrap manifest"><div><p className="eyebrow">UM AMBIENTE PARA A CLÍNICA</p><h2>Aprender, acompanhar e manter evidências no mesmo lugar.</h2><p className="lead">O portal separa a jornada de aprendizagem da operação administrativa e reúne os documentos próprios da clínica exigidos para LRSS.</p></div><div className="benefit-stack"><div><b>01</b><span><strong>Aulas em módulos</strong>Progresso salvo por aula.</span></div><div><b>02</b><span><strong>Documentos LRSS</strong>Envio, validade e revisão.</span></div><div><b>03</b><span><strong>Gestão contínua</strong>Alertas e histórico auditável.</span></div></div></div></section>
  <section className="section"><div className="wrap"><div className="price subscription-price"><span className="badge">PLANO PARA CLÍNICAS</span><h2>Acesso completo à plataforma</h2><div className="pricing-lines"><p><small>Inscrição</small><strong>R$ 299</strong></p><p><small>Mensalidade</small><strong>R$ 199</strong><span>/mês</span></p></div><p>Contrato de 24 meses. Valores e total são confirmados pelo servidor antes da contratação.</p><div className="notice">Ao avançar, você cria ou acessa a conta da clínica e aceita o contrato digital demonstrativo.</div><Link className="btn primary" href="/checkout">Criar conta e assinar</Link></div></div></section>
  <section className="section faq"><div className="wrap"><h2>Perguntas frequentes</h2><details><summary>É um software de prontuário ou agenda?</summary><p>Não. É uma plataforma de capacitação e acompanhamento de documentos próprios da clínica.</p></details><details><summary>Como funciona o acesso?</summary><p>A clínica cria uma conta no checkout. Após a contratação demonstrativa, os cursos e o portal são liberados.</p></details><details><summary>Os vídeos já usam um provedor?</summary><p>O MVP possui um player abstrato, pronto para integração futura com um provedor de vídeo seguro.</p></details></div></section>
  </>}
